### ISSUE TITLE
RuntimeError: The size of tensor a (4608) must match the size of tensor b (1536) at non-singleton dimension 2

### ISSUE THREAD

**Issue by BoBo0037** [fallenshock/FlowEdit#4]
Hi, on my macbook, i got this error, how to fix this?

Traceback (most recent call last):
  File "/Users/zhangbo/Desktop/FlowEdit/run_script.py", line 107, in <module>
    x0_tar = FlowEditFLUX(pipe,
             ^^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/Desktop/FlowEdit/FlowEdit_utils.py", line 349, in FlowEditFLUX
    Vt_src = calc_v_flux(pipe,
             ^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/Desktop/FlowEdit/FlowEdit_utils.py", line 95, in calc_v_flux
    noise_pred = pipe.transformer(
                 ^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 508, in forward
    encoder_hidden_states, hidden_states = block(
                                           ^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 180, in forward
    attn_output, context_attn_output = self.attn(
                                       ^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 588, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 2147, in __call__
    query = apply_rotary_emb(query, image_rotary_emb)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangbo/miniconda3/envs/bobo/lib/python3.11/site-packages/diffusers/models/embeddings.py", line 1159, in apply_rotary_emb
    out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
           ~~~~~~~~~~^~~~~
RuntimeError: The size of tensor a (4608) must match the size of tensor b (1536) at non-singleton dimension 2

**Comment by AbhinavJangra29** [comment]
```python
pip uninstall diffusers
```
```python
pip install diffusers==0.30.1
```

**Comment by xduzhangjiayu** [comment]
> pip uninstall diffusers
> pip install diffusers==0.30.1

Hi, how should I modify the FlowEdit code to make it compatible with the diffusers latest version? Thanks~

**Comment by RC-Wu** [comment]
Hello, what modifications were made to the diffusers library in the new version that caused this issue?
